In [1]:
import yfinance as yf
import streamlit as st
import pandas as pd

st.write("""first app""")

ticksymbol = 'GOOGL'
tickerData = yf.Ticker(ticksymbol)
tickerDf = tickerData.history(period='1d', start='2010-5-31', end='2020-5-31')
tickerDf

2020-12-02 21:36:59.796 INFO    numexpr.utils: NumExpr defaulting to 4 threads.


Open         High          Low        Close   Volume  \
Date                                                                      
2010-06-01   240.455460   245.775772   240.300293   241.426422  5328200   
2010-06-02   243.583588   247.182175   240.970978   246.931931  5076500   
2010-06-03   247.802795   254.254257   247.597595   253.053055  7294000   
2010-06-04   250.110107   254.879883   248.598602   249.609604  7832700   
2010-06-07   249.779785   250.705704   241.816818   243.003006  7258100   
...                 ...          ...          ...          ...      ...   
2020-05-22  1403.900024  1417.000000  1395.949951  1413.239990  1427200   
2020-05-26  1441.959961  1445.109985  1419.400024  1421.369995  2229500   
2020-05-27  1420.000000  1425.349976  1394.599976  1420.280029  1584200   
2020-05-28  1400.000000  1444.459961  1399.079956  1418.239990  1758500   
2020-05-29  1420.430054  1436.729980  1415.979980  1433.520020  1852200   

            Dividends  Stock Splits  
Date                                 
2010-06-01          0           0.0  
2010-06-02          0           0.0  
2010-06-03          0           0.0  
2010-06-04          0           0.0  
2010-06-07          0           0.0  
...               ...           ...  
2020-05-22          0           0.0  
2020-05-26          0           0.0  
2020-05-27          0           0.0  
2020-05-28          0           0.0  
2020-05-29          0           0.0  

[2517 rows x 7 columns]

In [3]:
import numpy as np
np.random.randn(1, 1)

array([[-1.84797199]])

In [6]:
last_rows = np.random.randn(1, 1)
last_rows

array([[-0.69798928]])

In [7]:
last_rows[-1,:]

array([-0.69798928])

In [9]:
np.random.randn(5, 1)

array([[ 1.17755202],
       [-0.24107879],
       [ 1.41643319],
       [ 1.10466969],
       [ 0.01230387]])

In [11]:
np.random.randn(5, 1).cumsum(axis=0)

array([[-2.07931257],
       [-3.90092015],
       [-3.58826325],
       [-4.49112626],
       [-4.90579468]])

In [14]:
last_rows[-1, :] + np.random.randn(5, 1).cumsum(axis=0)

array([[-0.1244429 ],
       [ 0.00458253],
       [ 1.00392011],
       [ 0.04276734],
       [-2.92695736]])

In [15]:
last_rows[-1, :] + np.array([1,2,3]).cumsum(axis=0)

array([0.30201072, 2.30201072, 5.30201072])

In [2]:
tickerDf.Close

Date
2010-06-01     241.426422
2010-06-02     246.931931
2010-06-03     253.053055
2010-06-04     249.609604
2010-06-07     243.003006
                 ...     
2020-05-22    1413.239990
2020-05-26    1421.369995
2020-05-27    1420.280029
2020-05-28    1418.239990
2020-05-29    1433.520020
Name: Close, Length: 2517, dtype: float64

In [16]:
df1 = pd.DataFrame()
l = []
for i in range(1000):
    l.append(i)
    
df1['close'] = l

# mychart = st.line_chart(df1['close'].iloc[0:1])
# for i in range(1000-1):
#     mychart.add_rows(df1['close'].iloc[i:i+1])

In [17]:
df1['close'].iloc[0:1]

0    0
Name: close, dtype: int64

In [19]:
df1['close'].iloc[i:i+1]

999    999
Name: close, dtype: int64

In [20]:
import SessionState


ModuleNotFoundError: No module named 'SessionState'

In [ ]:
import streamlit as st
import time
import numpy as np

progress_bar = st.sidebar.progress(0)
status_text = st.sidebar.empty()
last_rows = np.random.randn(1, 1)
chart = st.line_chart(last_rows)

for i in range(1, 101):
    new_rows = last_rows[-1, :] + np.random.randn(5, 1).cumsum(axis=0)
    status_text.text("%i%% Complete" % i)
    chart.add_rows(new_rows)
    progress_bar.progress(i)
    last_rows = new_rows
    time.sleep(0.05)

progress_bar.empty()

# Streamlit widgets automatically run the script from top to bottom. Since
# this button is not connected to any other logic, it just causes a plain
# rerun.
st.button("Re-run")

In [22]:
df2 = pd.DataFrame({'RPV_IF_1': [3],
                    'RPV_IF_2': [2],
                    'RPV_IF_3': [3.4],
                    'RPV_IF_4': [6],
                    'RPV_IF_5': [7]})

In [23]:
product_prices=[1,3,5,2,3]
product_prices.sort(reverse=True)

In [27]:
product_prices=[1,3,5,2,3]
p_p = product_prices.copy()

In [28]:
p_p.sort(reverse=True)

In [29]:
p_p

[5, 3, 3, 2, 1]

In [30]:
product_prices

[1, 3, 5, 2, 3]

In [33]:
import random
random.randint(1, 2)

1

In [70]:
random.sample(range(5,10), 2)

[6, 8]

In [44]:
random.randint(1, round(9/2))

ValueError: non-integer stop for randrange()

In [86]:
random.randint(0,1)

1

In [25]:
product_prices.index(3)

1

In [26]:
product_prices

[5, 3, 3, 2, 1]

In [88]:
np.random.rand()

0.8168873814600486

In [92]:
return_index=[]
sum([p for p in return_index])

0

In [90]:
list1 = []  
  
random.sample(list1,3)

ValueError: Sample larger than population or is negative

In [177]:
def user_simulator(product_prices, tra_rec_index, ins_rec_index, scenario, ins_level_rec):
    """
    product_prices: a list of prices of 10 recommended products
    tra_rec_index: a list of indices for the traditional recommended products
    ins_rec_index: a list of indices for the inspirational recommended products
    scenario: '1': more spontaneous,
              '2': more planned,
    ins_level_rec: inspirational factor the recommender used for generating the 10 rec products
    return the index of purchased items and the total order price
    """
    sort_prod_prices = product_prices.copy().sort(reverse=True)
    if tra_rec_index == [] or ins_rec_index == []: # if either is empty, i.e., the two extreme cases
        if np.random.rand() < 0.1:
            return_index = random.randint(0,9)
        else:
            return_index = []
    else:
        if scenario == '1': # scenario "spontaneous"
            if ins_level_rec == 0.4: # assume most users prefer 0.4 as inspiratioanl level
                return_index = random.sample(tra_rec_index, 1) + random.sample(ins_rec_index, 1)
            else:
                if np.random.rand() < 0.5:
                    return_index = random.sample(tra_rec_index, 1) + random.sample(ins_rec_index, 1)
                else:
                    return_index = random.sample(tra_rec_index, 1)
        else: # scenario "planned"
            if ins_level_rec == 0.1: # assume users prefer 0.1 as inspiratioanl level
                return_index = random.sample(tra_rec_index, 1)
            else:
                if np.random.rand() < 0.5:
                    return_index = random.sample(tra_rec_index, 1)
                else:
                    return_index = []
        # calculate totoal order price            
        if len(return_index) == 0:
            return_order_price = 0
        else:
            return_order_price = sum([product_prices[p] for p in return_index])
        
        return return_index, return_order_price 

In [158]:
random.sample(tra_rec_index, 1) + random.sample(ins_rec_index, 1)

[0, 4]

In [202]:
product_prices = [1, 2, 3, 4,1,2]
tra_rec_index= [0,1,3]
ins_rec_index= [2,4] 
scenario = '0', 
ins_level_rec = 0.4

In [231]:
user_simulator(product_prices=product_prices, \
               tra_rec_index=tra_rec_index, \
               ins_rec_index=ins_rec_index, \
               scenario='0', \
               ins_level_rec=ins_level_rec)

sc2


([], 0)

In [238]:
import uuid
import datetime
uuid.uuid4()
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
now

'2020-12-03 06:33:07'

In [241]:
t = random.sample(range(10, 30), 10)
t

[19, 10, 13, 24, 25, 28, 17, 15, 12, 23]

In [242]:
random.sample(range(1, 10), )

In [247]:
t[:1]

[17]

In [249]:
t[9:]

[24]

In [253]:
random.sample(range(1, 11), 10)

[10, 9, 7, 5, 8, 4, 6, 2, 1, 3]

In [257]:
# generate simulated data
df = pd.DataFrame(columns=['visitor_id', 'date_time', \
                           'location', 'ins_factor', \
                           'product_prices', 'tra_rec_index',\
                           'ins_rec_index', 'order_price'])
loc_list = ['Florida', 'Georgia', 'California', 'Texas', 'New York']
for i in range(1000):
    ins_factor = random.randint(1,10)
    rec_index = random.sample(range(1, 11), 10)
    df_delta = pd.DataFrame([[uuid.uuid4(), datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),\
                              random.sample(loc_list, 1)[0], ins_factor,\
                              random.sample(range(10, 30), 10), rec_index[ins_factor:],\
                              rec_index[:ins_factor], random.randint(0,100)]],\
                              columns=['visitor_id', 'date_time', \
                              'location', 'ins_factor', \
                              'product_prices', 'tra_rec_index',\
                              'ins_rec_index', 'order_price'])
    df = df.append(df_delta, ignore_index=True)
df

visitor_id            date_time    location  \
0    7026adfd-17c5-4a57-a487-9d299a59d54c  2020-12-03 06:51:44  California   
1    4c0ceaea-fcac-4a73-a02c-472864cb8bf8  2020-12-03 06:51:44       Texas   
2    000679bf-886c-4b8d-9331-bc9554145c86  2020-12-03 06:51:44       Texas   
3    8ae2e7cb-716d-4457-a250-e6e0b764239a  2020-12-03 06:51:44     Georgia   
4    5f8e1a94-fe38-4679-8691-cd455c5d73a9  2020-12-03 06:51:44     Florida   
..                                    ...                  ...         ...   
995  2da716f0-a9f6-4cfa-b991-d1680f06ea6c  2020-12-03 06:51:48     Florida   
996  f8b9e751-2f85-4b8a-9141-170de99bf1e4  2020-12-03 06:51:48     Florida   
997  8780b402-d941-4004-9f6d-8a6594e068d8  2020-12-03 06:51:48     Florida   
998  e40ba8d0-b592-48bc-8fba-f2c897288eb6  2020-12-03 06:51:48     Georgia   
999  7414a319-ffe7-4f5f-9ffa-955dec9197b4  2020-12-03 06:51:48    New York   

    ins_factor                            product_prices  \
0            8  [29, 14, 26, 23, 27, 10, 13, 17, 24, 18]   
1            9  [23, 19, 21, 27, 18, 12, 13, 17, 11, 10]   
2            8  [19, 18, 10, 12, 23, 27, 13, 26, 22, 14]   
3            7  [14, 16, 11, 13, 22, 17, 19, 26, 29, 20]   
4            9  [28, 12, 14, 29, 20, 22, 26, 15, 17, 16]   
..         ...                                       ...   
995          2  [19, 28, 18, 14, 17, 10, 20, 21, 16, 29]   
996          8  [17, 26, 15, 25, 18, 13, 11, 23, 21, 12]   
997          7  [21, 17, 14, 16, 15, 12, 26, 25, 24, 20]   
998          9  [24, 28, 13, 19, 15, 20, 27, 22, 29, 10]   
999          7  [29, 15, 23, 26, 12, 27, 20, 18, 17, 19]   

                 tra_rec_index                 ins_rec_index order_price  
0                       [5, 9]     [8, 10, 2, 1, 7, 6, 3, 4]          26  
1                          [4]  [9, 2, 10, 3, 8, 5, 6, 7, 1]          41  
2                       [2, 6]     [5, 10, 3, 1, 4, 8, 7, 9]          12  
3                   [8, 10, 1]         [5, 7, 3, 6, 4, 9, 2]          32  
4                          [1]  [7, 2, 10, 3, 9, 6, 5, 4, 8]          36  
..                         ...                           ...         ...  
995  [7, 1, 3, 5, 6, 10, 9, 8]                        [2, 4]          76  
996                     [7, 4]     [1, 6, 10, 8, 3, 9, 5, 2]          34  
997                 [8, 9, 10]         [2, 7, 6, 1, 4, 5, 3]          57  
998                       [10]   [1, 9, 3, 8, 7, 2, 5, 6, 4]          64  
999                 [2, 10, 9]         [3, 7, 8, 6, 1, 4, 5]          36  

[1000 rows x 8 columns]

In [264]:
t = "['1','2','3']"

In [265]:
list(t)

['[', "'", '1', "'", ',', "'", '2', "'", ',', "'", '3', "'", ']']

In [258]:
df.to_csv('./simulated_data.csv')

In [263]:
df.ins_factor.iloc[15]

10

In [262]:
df.order_price.iloc[i]

36